apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-env-example
spec:
  containers:
  - name: secret-pod-env-example
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: user-credential
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: user-credential
            key: password
  restartPolicy: Never