apiVersion: v1
kind: Pod
metadata:
  name: pod-front-example
  labels:
    app: pod-tier
    tier: frontend
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-back-example
  labels:
    app: pod-tier
    tier: backend
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2