apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    app: web-app
    role: frontend-app
spec:
  containers:
    - name: web-app
      image: nginx
      ports:
        - containerPort: 80