apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: say-hello
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: say-hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello Kubernetes CronJob
          restartPolicy: OnFailure