apiVersion: v1
kind: Service
metadata:
  name: distributed-service
  labels:
    app: distributed-service
spec:
  ports:
  - port: 80
    name: distributed-set
  clusterIP: None
  selector:
    app: distributed-service
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: distributed-set
spec:
  selector:
    matchLabels:
      app: distributed-service
  serviceName: "distributed-service"
  replicas: 6
  template:
    metadata:
      labels:
        app: distributed-service
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: distributed-set
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "first-storage-class"
      resources:
        requests:
          storage: 1Gi