apiVersion: batch/v1
kind: Job
metadata:
  name: job-hello-world
spec:
  template:
    spec:
      containers:
      - name: job-hello-world
        image: busybox
        command: ["echo",  "Hello World"]
      restartPolicy: Never
  backoffLimit: 4  # 退避限制，Job失败后的重试次数