apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: large
value: 1000000

---

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: medium
value: 500000

---

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: small
value: 10000