apiVersion: v1
kind: Pod
metadata:
  name: large-quota-pod
spec:
  containers:
  - name: large-quota-pod
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    resources:
      requests:
        memory: "16Gi"
        cpu: "500m"
      limits:
        memory: "16Gi"
        cpu: "500m"
  priorityClassName: large # 对应ResourceQuota对象中scopeSelector操作符中的values