apiVersion: v1
kind: Pod
metadata:
  name: hostaliases-example
spec:
  restartPolicy: Never
  hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "domailone.local"
    - "domaintwo.local"
  - ip: "10.3.2.1"
    hostnames:
    - "domainone.remote"
    - "domaintwo.remote"
  containers:
  - name: cat-on-etc-hosts
    image: busybox
    command:
    - cat
    args:
    - "/etc/hosts"